version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: investments-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: investments_db
      MYSQL_USER: investments_user
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: